# Generated by Django 6.0 on 2025-12-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('student_department', models.CharField(max_length=30)),
                ('student_course', models.CharField(max_length=30)),
            ],
        ),
    ]
