# Generated by Django 6.0 on 2025-12-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_designation', models.CharField(max_length=30)),
                ('staff_courses', models.CharField(max_length=40)),
            ],
        ),
    ]
