# Generated by Django 6.0 on 2025-12-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_designation', models.CharField(max_length=30)),
                ('employee_salary', models.FloatField()),
            ],
        ),
    ]
